# Generated by Django 4.1.5 on 2023-01-26 07:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logbook', '0002_student_registration_number_user_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True)),
                ('report', models.TextField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logbook.student')),
            ],
        ),
        migrations.CreateModel(
            name='DairyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True)),
                ('activity', models.TextField()),
                ('workin_hours', models.IntegerField(verbose_name='Workin Hours')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logbook.student')),
            ],
        ),
    ]
