# Generated by Django 4.1.5 on 2023-01-27 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logbook', '0004_rename_dairyreport_dailyreport_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_teacher',
            new_name='is_supervisor',
        ),
    ]
